services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: tsukuyomi
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5433:5432"

volumes:
  db_data:
