services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: tsukuyomi
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
